app-db:
  build: ./db
  container_name: postgres-docker
  restart: always
  ports:
    - "5432:5432"
  volumes_from:
    - app-db-data


app-web:
  build: .
  container_name: web-docker
  ports:
    - "8080:8080"
  links:
    - app-db



app-db-data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
      - /var/lib/postgresql/data